import { motion } from "framer-motion";
import { Server, CheckCircle2, ArrowRight, Star, Database, Shield, Zap } from "lucide-react";
import { NavLink, type MetaFunction } from "react-router";
import { buildPageMeta, SITE_AUTHOR, SITE_URL } from "~/lib/seo";

export const meta: MetaFunction = () => [
    ...buildPageMeta({
        title: "Backend API Development India | REST API & Microservices Expert - Dhanraj Pimple",
        description:
            "Expert backend API development in India. REST APIs, microservices, GraphQL, FastAPI, Node.js, PostgreSQL, Redis, JWT auth, and cloud deployment. Serving startups and enterprises globally from Pune, Maharashtra.",
        path: "/backend-api-development",
        keywords:
            "backend API developer India, REST API developer India, FastAPI developer India, Node.js backend developer, microservices developer India, API development India, hire backend developer India, GraphQL developer India",
    }),
    { "script:ld+json": { "@context": "https://schema.org", "@type": "Service", name: "Backend API Development", provider: { "@type": "Person", name: SITE_AUTHOR, url: SITE_URL }, serviceType: "Backend Development", description: "REST API, GraphQL, and microservices development using FastAPI, Node.js, PostgreSQL, Redis, with cloud deployment.", areaServed: ["India", "Global"] } },
];

const faqs = [
    { q: "What backend technologies do you work with?", a: "FastAPI (Python), Node.js (Express/Fastify), PostgreSQL, MongoDB, Redis, Supabase, and GraphQL. I choose the right tech for your use case." },
    { q: "Can you build a secure API with authentication?", a: "Yes. JWT auth, OAuth2, API key management, rate limiting, CORS, and input validation — all production-ready from day one." },
    { q: "Do you document the APIs you build?", a: "Yes. Every API project includes automatic OpenAPI (Swagger) docs generated by FastAPI, or I use Postman collections for Node.js APIs." },
    { q: "How long does backend API development take?", a: "A basic CRUD API with auth: 1–2 weeks. Complex APIs with payments, file uploads, background jobs: 3–6 weeks." },
];

export default function BackendApiDevelopment() {
    return (
        <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="container mx-auto px-6 py-16 space-y-24 max-w-6xl">
            <section className="glass p-10 md:p-16 rounded-3xl relative overflow-hidden border border-brand-blue/20">
                <div className="absolute top-0 right-0 w-80 h-80 bg-brand-blue/10 blur-3xl -translate-y-1/2 translate-x-1/2" />
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-brand-blue/20 text-brand-blue mb-6">
                    <Server size={16} />
                    <span className="text-xs font-bold uppercase tracking-wider">REST API · GraphQL · Microservices</span>
                </div>
                <h1 className="text-4xl md:text-6xl font-display font-bold mb-6 leading-tight">
                    Backend API Development <span className="text-gradient">for Scalable Products</span>
                </h1>
                <p className="text-lg text-brand-gray mb-4 max-w-3xl leading-relaxed">
                    Build fast, secure, and scalable backend APIs with a dedicated backend developer in India. I design and ship
                    REST APIs, GraphQL APIs, and microservices using FastAPI, Node.js, PostgreSQL, and Redis — with full
                    documentation, authentication, and cloud deployment.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 mt-8">
                    <NavLink to="/contact" className="px-8 py-4 bg-brand-blue text-brand-navy font-bold rounded-xl flex items-center justify-center gap-2 hover:bg-brand-coral hover:text-white transition-all shadow-xl shadow-brand-blue/20">
                        Start Your API Project <ArrowRight size={20} />
                    </NavLink>
                    <NavLink to="/hire-fastapi-developer" className="px-8 py-4 glass border border-white/10 text-white font-bold rounded-xl flex items-center justify-center gap-2 hover:bg-white/10 transition-all">
                        Hire FastAPI Developer
                    </NavLink>
                </div>
            </section>

            <section>
                <h2 className="text-3xl md:text-4xl font-display font-bold mb-10">Backend API Development Services</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {[
                        { icon: <Server />, title: "REST API Design & Development", desc: "Versioned REST APIs with proper HTTP semantics, OpenAPI documentation, request validation, and consistent response formats." },
                        { icon: <Database />, title: "Database Design & ORM Setup", desc: "PostgreSQL, MongoDB, or Redis with SQLAlchemy/Prisma ORM, Alembic migrations, and query optimization." },
                        { icon: <Shield />, title: "Authentication & Authorization", desc: "JWT, OAuth2, API key management, RBAC, refresh token rotation, and social login integration." },
                        { icon: <Zap />, title: "Background Jobs & Queues", desc: "Celery, BullMQ, or FastAPI BackgroundTasks for async email, file processing, and scheduled jobs." },
                    ].map((item) => (
                        <div key={item.title} className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/5">
                            <div className="text-brand-blue shrink-0 mt-1">{item.icon}</div>
                            <div>
                                <h3 className="font-bold mb-2 text-brand-offwhite">{item.title}</h3>
                                <p className="text-xs text-brand-gray leading-relaxed">{item.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            <section>
                <h2 className="text-3xl md:text-4xl font-display font-bold mb-10 text-center">FAQ — Backend API Development</h2>
                <div className="space-y-6 max-w-3xl mx-auto">
                    {faqs.map((faq, i) => (
                        <motion.div key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.06 }} viewport={{ once: true }}
                            className="glass p-8 rounded-2xl border border-white/5">
                            <p className="font-bold text-brand-offwhite mb-3">{faq.q}</p>
                            <p className="text-brand-gray text-sm leading-relaxed">{faq.a}</p>
                        </motion.div>
                    ))}
                </div>
            </section>

            <section className="glass p-10 rounded-3xl border border-brand-blue/20 text-center">
                <h2 className="text-2xl font-display font-bold mb-6">Ready to Build Your Backend API?</h2>
                <div className="flex flex-wrap justify-center gap-3 mb-8">
                    {["FastAPI & Node.js expert", "OpenAPI docs included", "Fixed-price delivery", "JWT & OAuth2 setup"].map((t) => (
                        <span key={t} className="flex items-center gap-2 px-4 py-2 glass rounded-full text-sm border border-white/10"><Star size={14} className="text-brand-blue" /> {t}</span>
                    ))}
                </div>
                <NavLink to="/contact" className="px-10 py-4 bg-brand-blue text-brand-navy font-bold rounded-xl inline-flex items-center gap-2 hover:bg-brand-coral hover:text-white transition-all">
                    Get a Free API Consultation <ArrowRight size={20} />
                </NavLink>
            </section>

            <section className="border-t border-white/5 pt-12">
                <h2 className="text-xl font-bold mb-6">Related Services</h2>
                <div className="flex flex-wrap gap-4">
                    <NavLink to="/hire-fastapi-developer" className="px-6 py-3 glass rounded-xl text-sm font-bold hover:border-brand-blue/40 border border-white/10 transition-all">Hire FastAPI Developer →</NavLink>
                    <NavLink to="/ai-saas-development" className="px-6 py-3 glass rounded-xl text-sm font-bold hover:border-brand-blue/40 border border-white/10 transition-all">AI SaaS Development →</NavLink>
                    <NavLink to="/hire-devops-engineer" className="px-6 py-3 glass rounded-xl text-sm font-bold hover:border-brand-blue/40 border border-white/10 transition-all">Hire DevOps Engineer →</NavLink>
                </div>
            </section>
        </motion.main>
    );
}
